---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: comment-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comment
  template:
    metadata:
      name: comment
      labels:
        app: comment
    spec:
      containers:
#      - image: ${USER_NAME}/comment:${VER_COMMENT}
      - image: deribinvladimir/comment:latest
        name: comment
